version: '2'
services:
  db:
    image: mongo:latest
    stdin_open: true
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
    container_name: db.feedflow.io

  api:
    image: node:latest
    stdin_open: true
    volumes:
      - ./api.feedflow.io:/opt/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    container_name: api.feedflow.io
